/** Learn-screen entries for the advanced techniques in techniques/advanced.ts. */
import type { TechniqueInfo } from "./hint-types";

export const ADVANCED_CATALOG: readonly TechniqueInfo[] = [
  {
    id: "x-wing",
    name: "X-Wing",
    family: "sudoku",
    tier: 3,
    rating: 3.2,
    summary: "Two rows whose only places for a digit fall in the same two columns (or two columns, same two rows).",
    spot: "Pick a digit. Find two rows where it has exactly two possible cells, and those cells line up in the same two columns — the corners of a rectangle. Columns work the same way.",
    why: "Each row needs the digit once, and the two rows can't use the same column. So one row takes it in the first column and the other in the second: both columns get their digit from these two rows, and no other cell in those columns can hold it.",
    tip: "Go one digit at a time and note the rows (or columns) where it has only two spots — X-wings hide among those pairs.",
  },
  {
    id: "swordfish",
    name: "Swordfish",
    family: "sudoku",
    tier: 3,
    rating: 3.8,
    summary: "Three rows whose candidates for a digit all fit in the same three columns.",
    spot: "Pick a digit and find three rows where it has only two or three places, all within the same three columns. Not every row needs all three. Columns work the same way.",
    why: "The three rows need three of that digit, in three different columns, so they use up the digit in all three columns. Every other cell in those columns loses it.",
    tip: "If an X-wing is a rectangle, a swordfish is the 3×3 version — usually with some corners missing.",
  },
  {
    id: "jellyfish",
    name: "Jellyfish",
    family: "sudoku",
    tier: 4,
    rating: 5.2,
    summary: "Four rows whose candidates for a digit all fit in the same four columns.",
    spot: "The four-line big sister of the X-wing and swordfish: four rows where a digit is confined to the same four columns, or four columns confined to the same four rows.",
    why: "Four rows need four of the digit in four different columns, which uses up the digit in those columns. The rest of the four columns can't hold it.",
    tip: "Rare. When one exists, a smaller fish often shows up in the other direction too.",
  },
  {
    id: "finned-x-wing",
    name: "Finned X-Wing",
    family: "sudoku",
    tier: 3,
    rating: 3.4,
    summary: "An X-wing spoiled by an extra candidate or two (the fin) in one corner's box.",
    spot: "Look for two rows that would form an X-wing on a digit except for one or two extra candidates, all in the same box as one of the corners.",
    why: "Either a fin holds the digit, or the X-wing is real. A cell that lies in the X-wing's columns and also sees every fin loses the digit both ways.",
    tip: "The eliminations are always close to the fin: inside the fin's box, on the X-wing's columns. If a corner is missing altogether it's a sashimi X-wing, and the same logic works.",
    aka: ["Sashimi X-Wing"],
  },
  {
    id: "finned-swordfish",
    name: "Finned Swordfish",
    family: "sudoku",
    tier: 4,
    rating: 4.0,
    summary: "A swordfish with an extra candidate or two (the fin) in one box.",
    spot: "Three rows that would make a swordfish on a digit except for a few extra candidates, all in one box.",
    why: "Either a fin holds the digit or the swordfish is real. Cells in the swordfish's columns that also see every fin lose the digit either way.",
    tip: "As with the finned X-wing, look in the fin's box for the eliminations.",
    aka: ["Sashimi Swordfish"],
  },
  {
    id: "skyscraper",
    name: "Skyscraper",
    family: "sudoku",
    tier: 3,
    rating: 3.3,
    summary: "Two rows (or columns) with exactly two places for a digit, one end of each lined up.",
    spot: "Find two parallel lines where a digit appears exactly twice. If one candidate from each sits in the same column — the base — the other two are the tops of the towers.",
    why: "The two base cells can't both hold the digit, so at least one tower's top must. Any cell that sees both tops can't hold it.",
    tip: "The eliminations sit where the two tops' rows, columns and boxes overlap.",
    aka: ["Turbot Fish"],
  },
  {
    id: "two-string-kite",
    name: "2-String Kite",
    family: "sudoku",
    tier: 3,
    rating: 3.35,
    summary: "A row and a column with exactly two places for a digit, tied together in one box.",
    spot: "Find a row and a column where a digit appears exactly twice each, with one candidate of each in the same box (in different cells).",
    why: "The two cells in the box can't both hold the digit, so one of the far ends must. The cell that sees both far ends — where the far ends' column and row cross — can't hold it.",
    aka: ["Turbot Fish"],
  },
  {
    id: "empty-rectangle",
    name: "Empty Rectangle",
    family: "sudoku",
    tier: 4,
    rating: 4.5,
    summary: "A box whose candidates for a digit all lie on one row and one column, used with a pair outside the box.",
    spot: "Find a box where a digit only appears on one row and one column of the box (an L, T or + shape, leaving an empty rectangle). Then find a line outside the box with exactly two places for the digit, one of them on the box's row or column.",
    why: "If the near end of that pair holds the digit, the box's digit is pushed onto its other line. If not, the far end holds it. The cell where the far end's line crosses the box's other line sees the digit either way.",
    aka: ["ER"],
  },
  {
    id: "xy-wing",
    name: "XY-Wing",
    family: "sudoku",
    tier: 3,
    rating: 4.2,
    summary: "A two-candidate cell {X,Y} that sees two other two-candidate cells, {X,Z} and {Y,Z}.",
    spot: "Pick a cell with two candidates — the pivot. Among the cells it sees, find one that shares its first digit and one that shares its second, both with the same other digit Z.",
    why: "Whatever the pivot turns out to be, one of the two pincers becomes Z. So a cell that sees both pincers can't be Z.",
    tip: "Two-candidate cells are the raw material for wings and chains. It pays to spot them early.",
    aka: ["Y-Wing", "Bent triple"],
  },
  {
    id: "xyz-wing",
    name: "XYZ-Wing",
    family: "sudoku",
    tier: 3,
    rating: 4.4,
    summary: "Like an XY-wing, but the pivot also holds Z: {X,Y,Z} with pincers {X,Z} and {Y,Z}.",
    spot: "Find a three-candidate cell that sees two two-candidate cells made from its digits, sharing one digit Z.",
    why: "One of the three cells must be Z: if the pivot is X or Y, a pincer becomes Z, and otherwise the pivot is Z. Cells that see all three can't be Z.",
    tip: "The eliminations are always in the pivot's box, alongside the pivot.",
  },
  {
    id: "w-wing",
    name: "W-Wing",
    family: "sudoku",
    tier: 4,
    rating: 4.4,
    summary: "Two identical two-candidate cells {X,Y} joined by a house with only two places for X.",
    spot: "Find two cells with the same two candidates that don't see each other. Then look for a row, column or box where X has only two places, one seen by each cell.",
    why: "If the first cell isn't Y, it's X; that pushes X along the link and stops the second cell being X, so it's Y. One of the two cells is Y, so cells that see both can't be Y.",
  },
  {
    id: "simple-coloring",
    name: "Simple Colouring",
    family: "sudoku",
    tier: 4,
    rating: 4.5,
    summary: "Chain the places where a digit comes in pairs, colouring them in two alternating colours.",
    spot: "Pick a digit. Join the cells that are the only two places for it in a row, column or box, and colour along the chain, switching colour at each step.",
    why: "Exactly one colour holds the digit. If two cells of the same colour see each other, that colour is false and all its cells lose the digit (colour wrap). A cell that sees both colours can't hold it either (colour trap).",
    tip: "Stick to one digit at a time. Long chains of pairs are common in harder puzzles.",
    aka: ["Singles Chains", "Colour Wrap", "Colour Trap"],
  },
  {
    id: "unique-rectangle",
    name: "Unique Rectangle",
    family: "sudoku",
    tier: 4,
    rating: 4.5,
    summary: "Steer clear of a 'deadly pattern' — four cells that could swap two digits.",
    spot: "Look for four cells at the corners of a rectangle spanning two rows, two columns and two boxes, all holding the same two candidates, where one or two corners have extras.",
    why: "If all four corners ended up as just those two digits, they could be swapped and the puzzle would have two solutions. A proper puzzle has one, so the extras must matter: a lone corner with extras can't be either pair digit, and two corners with the same single extra must have it in one of them.",
    tip: "Only valid for puzzles with exactly one solution, so it isn't used in killer.",
    aka: ["UR", "Uniqueness test"],
  },
  {
    id: "bug-plus-one",
    name: "BUG+1",
    family: "sudoku",
    tier: 4,
    rating: 5.6,
    summary: "Every empty cell has two candidates except one; that cell takes the digit it holds three of in its houses.",
    spot: "Late in a puzzle, when almost every cell is down to two candidates, look for a lone cell with three.",
    why: "If every cell had two candidates and every digit two places in each house, the board would have two solutions or none — a 'bivalue universal grave'. The odd cell's extra digit is what prevents that, so it must go there.",
    tip: "Like unique rectangles, it relies on the puzzle having one solution.",
    aka: ["Bivalue Universal Grave"],
  },
  {
    id: "x-chain",
    name: "X-Chain",
    family: "sudoku",
    tier: 5,
    rating: 6.0,
    summary: "A chain on one digit that alternates 'only two places' links with 'can't both be' links.",
    spot: "Pick a digit. Start at a cell, jump to the other place in a house where the digit has only two places, then to a cell that sees it, then along another pair, and so on. End with a pair link.",
    why: "If the first cell isn't the digit, the pair forces the next one to be; that rules out the next; and so on until the last cell must be the digit. So at least one end holds it, and any cell that sees both ends can't.",
    tip: "Skyscrapers and 2-string kites are the shortest X-chains.",
    aka: ["X-Cycle"],
  },
  {
    id: "xy-chain",
    name: "XY-Chain",
    family: "sudoku",
    tier: 5,
    rating: 6.2,
    summary: "A chain of two-candidate cells, each seeing the next, that starts and ends on the same digit.",
    spot: "Start at a two-candidate cell holding Z. Its other digit leads to a two-candidate cell it sees that shares that digit; that cell's other digit leads on to the next. Stop at a cell holding Z.",
    why: "If the first cell isn't Z, each cell in turn is forced to its other digit, and the last cell becomes Z. One end is Z, so cells that see both ends can't be.",
    tip: "An XY-wing is the shortest XY-chain.",
  },
  {
    id: "aic",
    name: "Alternating Inference Chain",
    family: "sudoku",
    tier: 5,
    rating: 6.6,
    summary: "A chain that mixes 'only two places in a house' and 'only two candidates in a cell' links, across digits.",
    spot: "Alternate strong links (if one isn't true, the other is) with weak links (they can't both be true), hopping between candidates of any digits. Start and end with a strong link.",
    why: "If the first candidate is false, the chain forces the last one to be true. So at least one end is true, and anything that can't coexist with either end can go.",
    tip: "Same digit at both ends: cells that see both lose it. Different digits in cells that see each other: each end cell loses the other end's digit.",
    aka: ["AIC", "Nice Loop"],
  },
];
